const functions = require("firebase-functions");
const admin = require("firebase-admin");
const { VertexAI } = require("@google-cloud/vertexai");

admin.initializeApp();

// Initialize Vertex AI with your project details
// NOTE: Make sure the Vertex AI API is enabled in your Google Cloud project.
const vertex_ai = new VertexAI({
  project: process.env.GCLOUD_PROJECT, // Your GCP project ID
  location: "us-central1",
});

const generativeModel = vertex_ai.getGenerativeModel({
  model: "gemini-1.0-pro",
});

exports.generateMusicProfile = functions.https.onCall(async (data, context) => {
  // 1. Ensure user is authenticated
  if (!context.auth) {
    throw new functions.https.HttpsError(
      "unauthenticated",
      "You must be logged in to call this function."
    );
  }
  const userId = context.auth.uid;

  // 2. Fetch user's listening history from Firestore (last 100 songs)
  const historySnapshot = await admin.firestore()
    .collection("users").doc(userId)
    .collection("listening_history")
    .orderBy("timestamp", "desc").limit(100).get();

  if (historySnapshot.empty) {
    return "No listening history found. Go listen to some music!";
  }

  // 3. Format the data for the AI prompt
  const songs = historySnapshot.docs.map((doc) => doc.data());
  const historyText = songs.map((s) => `${s.artist} - ${s.songTitle} (Genre: ${s.genre})`).join("\n");

  // 4. Create the detailed prompt for Gemini
  const prompt = `
        You are a "Music Taste Analyst" inspired by Spotify Wrapped.
        Analyze the following list of recently played songs and generate a fun, insightful, and personalized profile for the user.
        The response should be a single block of text.
        
        - Start with a catchy, creative headline for their music personality (e.g., "The Genre-Hopping Adventurer" or "The Nostalgic Rockstar").
        - Identify their top 3 genres and describe how they blend together in the user's taste.
        - Mention their top 1-2 most played artists and why they might appeal to the user.
        - Describe the overall mood or vibe of their music (e.g., "Your playlist is perfect for a late-night drive, full of upbeat energy and introspective moments.").
        - End with a fun, conclusive statement about their unique taste.
        
        Keep the tone engaging, positive, and a little playful. Here is the user's listening history:
        ---
        ${historyText}
        ---
    `;

  // 5. Call Gemini and return the result
  try {
    const resp = await generativeModel.generateContent({ contents: [{ role: "user", parts: [{ text: prompt }] }] });
    if (resp.response.candidates && resp.response.candidates.length > 0) {
      const profileText = resp.response.candidates[0].content.parts[0].text;
      return profileText;
    } else {
      throw new Error("No content generated by AI.");
    }
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw new functions.https.HttpsError("internal", "Failed to generate profile from AI.", error.message);
  }
});